### ISSUE TITLE
Madry model

### ISSUE THREAD

**Issue by yyyyxie** [uriyapes/pnml_adv#1]
Hi, did you finally successfully convert Madry secret model from Tensorflow to PyTorch? Thanks!

**Comment by uriyapes** [comment]
Hi, sorry for the late reply. After realizing converting the model with MMdnn is a big headache I decided not to do it. Instead, I trained the model on my own but the performance wasn't as good as in Madry case. 

I suggest using https://github.com/yaircarmon/semisup-adv model, it uses WRN-28-10 architecture as well and the performance is great (better than Madry).
